#!/usr/bin/ruby
from = ARGV[0].match(/from:(\S*)\](.*)/)
to = ARGV[0].match(/to:(\S*)\](.*)/)
flags = ARGV[0].match(/flags:(\S*)\](.*)/)
# index 0 is the whole pattern that was matched
from = from[1] # this is the first () group
to = to[1] # this is the first () group
flags = flags[1] # this is the first () group
print from + "," + to + "," + flags + "\n"
