access_key_id: 'AKIAITH3HBCL6H2KNXXQ'
secret_access_key: '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'
key_pair: 'MIIEowIBAAKCAQEA5Wur98TW1iTokjIcIPygPZq17NDlTJfsrVCNRpkiIXvo+M3V51sGQJ+StxaL
VAbzK5qmfkcOw7Yn+UGmr2a16xvyfCCEccPg/vHMRAX/EJX/oS7niG6ReP0RwYsBVFTWrIcQSMVD
LkX3eKBHmcEvrhjnalYJaE2KqkqbMVsc3hZduy7mDoKFwRxUphiLkuJAp1Plu3V6Ontauq/HOFWx
iR/iP/UyHtL1zTmwjLkUAh4qaY3dCqP+c2Ddezeg14bb9kP6O2CBdtKP3L9QID8rmUj/XCIkI4NU
6OZpZ1Bg6nH1xyp0L6Xs4iaS0s3gDzGWMe/rx8nG9oZ8DBH2lv1GPwIDAQABAoIBAFyZPOvgkyYT
95sqhpf532N+EnfnSOXFXE4H+T3JiTEipkHmMrQS1U84GSu0+b+MnpG29gR6AceUukWs7e5V8o9W
1GSta0fP2/yK8/twwCadpHQWTnWOy0CeRJBt3rd/FrbEPRpiJF+E9gHGD6BLjUcj3iPZXiqvQYzC
WClvsRMiCEDmRW07kAGv6HRXHioGP9eVnAAzZXt+MBT4mojJ4wqsPlkI2Y0VMjgFZmshFqHo3Aeb
16M7jBvo0SugaON4pSUJM0Xk2yk2jEFebmG8TH4OQIhSfQ3UuTumdrCttyRwDZ9+7jGXGD3AaAFR
rL99cZo/z69Sk7tEm6mzyEM81GECgYEA9qgLq/m7XGpq5PrZTFKqy6Cu+FYoQBTUh4KeT9qfQhH1
ICRtbip2meWkuqvOtqruauydn553XTaz1XBhfJ1l9h4lbYsHcS2QiN6yy8+p/f2GaMkpljgNvYXk
h7bbfDjfMB3zdgAoiq4JLrKhD0Q6YaYlM77JymK3PSH3rH8IhvsCgYEA7hx7PA9tGzJh5twRCjRx
vSDCs1l2NNq1iiO87MPUcEXk37WmKvKNrzNETO+Xixt/g47TDwQqAPnjrologVRmG7brt9xwb2tY
qM7LcezV69CJRRmUqkDq26G5HqscSL4L15a+d55swjNBw1bvjcWQQq3EWflqfdFRrPMDATWFao0C
gYBoHt32ddAqnd2L1Xx/JHJmzOiveic5jdF9dpz/lokd6diw/c+X7qLsKi2Ug0wafiNwzXtoUwuO
NLZLRkpQwVy2PVmNWWAF3bcin+eX84yN5ESl3S0J9ZWPSIME6yLR2GwWsr4ANOboS7killM4z5NZ
fzo7ErG6FlvFmZ4kmedumwKBgQCOUi/GomHQk7i4yGjW9KnXJbG6iYqB5QgFXX8a9aIQyXYX0PdV
TE0rnzT/12V5HCKHe+LjYtXIZ5STSkZQpyWxAxC5gOUjc8I2hAROQAVNQgQKbVPSv6KhTHTdw+DQ
CegCIHQQA312RjTUkS32S1QCxuJJ9S6VrXtoKIhvPJJWMQKBgHlK/lvE93fKljGq9FL9FgU16Ho3
DgMSs6demkgnWCV381Rvi2A9tae0KdMJVybNDtcxvnpjexRxarLTVrB2ZAMeIybaYybFU7sBGyqh
TKtuJOle8XKgpDuyE+Zfge4pOt7pAYKhltZvVP2k7GsSGG8kW3+raOiEkIHH21I/t77/'
image_id: 'ami-7172b611'
instance_type: 't2.micro'
availability-zone: 'us-west-2a'
security_group_ids: ['sg-dc0e24ba']

# User Name:
# Bennett
#
# Access Key ID:
# AKIAITH3HBCL6H2KNXXQ
#
# Secret Access Key:
# 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
